//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CommonMsgSrv
{
    [Serializable]
    public class SendBoolResponse : Message
    {
        public const string k_RosMessageName = "common_msg_srv/SendBool";
        public override string RosMessageName => k_RosMessageName;

        public bool status;

        public SendBoolResponse()
        {
            this.status = false;
        }

        public SendBoolResponse(bool status)
        {
            this.status = status;
        }

        public static SendBoolResponse Deserialize(MessageDeserializer deserializer) => new SendBoolResponse(deserializer);

        private SendBoolResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "SendBoolResponse: " +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
