//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CommonMsgSrv
{
    [Serializable]
    public class SendBoolRequest : Message
    {
        public const string k_RosMessageName = "common_msg_srv/SendBool";
        public override string RosMessageName => k_RosMessageName;

        public bool request;

        public SendBoolRequest()
        {
            this.request = false;
        }

        public SendBoolRequest(bool request)
        {
            this.request = request;
        }

        public static SendBoolRequest Deserialize(MessageDeserializer deserializer) => new SendBoolRequest(deserializer);

        private SendBoolRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.request);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.request);
        }

        public override string ToString()
        {
            return "SendBoolRequest: " +
            "\nrequest: " + request.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
